Implement active config-jdbc #49
quarkiverse/quarkus-config-extensions pull request #50
Opened 2022-01-12 18:57 UTC by aster-phoenix

This is a prototype implementation of #49, by introducing  `quarkus.config.source.jdbc.cache` configuration which defaults to true to choose between in-memory or actively getting values from database

2022-01-13 15:03 UTC, radcortez commented
I'm not totally sure if it is a good idea for the source to do a lookup on each configuration lookup. This can potentially explode the number of queries being executed, especially at startup.

Also, we have to remember that changing a configuration does not mean that Quarkus will change its behavior. For instance, don't expect Quarkus to change the `http.port` if the value changes. Probably this is most suited for user configuration, but we need to be careful to not give the impression that all configuration is reloadable.

2022-01-14 08:23 UTC, aster-phoenix commented
Your points are valid. The use case for this is not Quarkus configurations, but mainly the business specific configuration which can be reloadable.

2022-01-14 16:55 UTC, radcortez commented
If we are going to move forward with this, I think we need to hook up with the default Quarkus datasource provider, instead of having something completely set on the side. 

This means that we need to move this source to be runtime only, because data sources are not available during static init (and that was one of the reasons we created our own datasource, but only for the purposes of filling the config and then discarded). With this change, the datasource will be long-lived, and potentially if the user creates its own instances of `Config`, we will just be pilling up connection pools.

2022-01-22 14:37 UTC, aster-phoenix commented
Hi @radcortez, Sorry for the late response, I have updated the PR, unfortunately I have no experience building Quarkus extensions, I tried to use `BeanContainerBuildItem` to access the default datasource, but I always ended up in a cycle detected error, I am now accessing the datasource directly using `CDI.current()` but this does throw some exceptions around.

It does work as it is, but if there are better ways, please point me in the right direction.
thanks!

2022-01-24 20:44 UTC, radcortez commented
> Hi @radcortez, Sorry for the late response, I have updated the PR, unfortunately I have no experience building Quarkus extensions, I tried to use `BeanContainerBuildItem` to access the default datasource, but I always ended up in a cycle detected error, I am now accessing the datasource directly using `CDI.current()` but this does throw some exceptions around.

Ah, I thought that the datasource was created at static init, but it is created during runtime init, so after both Config instances (static and runtime).

> It does work as it is, but if there are better ways, please point me in the right direction. thanks!

The only real way to do this properly is to revert back and create our own datasource, but it needs to be exposed as a configuration, so it can be tuned properly if required.

Sorry for the inconvenience :(

2022-01-25 08:19 UTC, aster-phoenix commented
> The only real way to do this properly is to revert back and create our own datasource, but it needs to be exposed as a configuration, so it can be tuned properly if required.

Could you please elaborate more on this? What should be exposed?

2022-01-25 16:35 UTC, radcortez commented
> > The only real way to do this properly is to revert back and create our own datasource, but it needs to be exposed as a configuration, so it can be tuned properly if required.
> 
> Could you please elaborate more on this? What should be exposed?

The datasource configuration. In the current main implementation, we reuse the properties for username, password, connection etc. But the the pool configuration is fixed:

https://github.com/quarkiverse/quarkus-config-extensions/blob/1ba4be4751d3867a59996aadde57fe623e2052ff/jdbc/runtime/src/main/java/io/quarkiverse/config/jdbc/runtime/Repository.java#L53-L72

So I think we need to expose some of this configuration, so we can tune the pool. We probably need to set aside the connection as well, in case the connection for the config doesn't match the quarkus config source. This is mostly to avoid confusion on how to configure the required datasource for config.

2022-01-29 16:48 UTC, aster-phoenix commented
@radcortez I have updated the PR, please check

2022-02-07 20:07 UTC, radcortez requested changes

2022-02-07 20:08 UTC, radcortez commented
> @radcortez I have updated the PR, please check

Thank you for the update. I believe we may have some issues regarding thread safety. Can you verify? Thanks!

2022-02-19 17:40 UTC, aster-phoenix commented
> Thank you for the update. I believe we may have some issues regarding thread safety. Can you verify? Thanks!

Hopefully it's in a better state now.

2022-03-02 13:00 UTC, aster-phoenix commented
> @aster-phoenix Sorry for taking some time. There are some compile issues. Can you please fix them? Thank you!

@radcortez sorry about that, fixed

2022-03-02 15:35 UTC, radcortez requested changes

2022-03-02 15:35 UTC, radcortez commented on jdbc/runtime/src/main/java/io/quarkiverse/config/jdbc/runtime/JdbcConfigSourceFactory.java
> +    JdbcConfigConfig config;
These should be local variables to the `getConfigSources` method. It prevents the factory to be discarded when is not needed anymore. Only the `ConfigSource` is required.

2022-03-02 15:35 UTC, radcortez commented on jdbc/runtime/src/main/java/io/quarkiverse/config/jdbc/runtime/JdbcConfigSourceFactory.java
> +    JdbcConfigConfig config;
Also, when we are caching the config, the `Repository` is only required to populate the `ConfigSource`. After that, it can be discarded.

2022-03-02 15:35 UTC, radcortez commented on jdbc/runtime/src/main/java/io/quarkiverse/config/jdbc/runtime/Repository.java
> +        final String selectAllQuery = new StringBuilder("SELECT conf.").append(config.keyColumn.get())
The database statement can be cached.

2022-03-02 15:35 UTC, radcortez commented on jdbc/runtime/src/main/java/io/quarkiverse/config/jdbc/runtime/Repository.java
> +        final String selectKeysQuery = new StringBuilder("SELECT conf.").append(config.keyColumn.get())
The database statement can be cached.

2022-03-02 15:35 UTC, radcortez commented on jdbc/runtime/src/main/java/io/quarkiverse/config/jdbc/runtime/Repository.java
> +        final String selectValueQuery = new StringBuilder("SELECT conf.").append(config.valueColumn.get())
The database statement can be cached.

2022-03-02 15:36 UTC, radcortez commented
> @radcortez sorry about that, fixed!

Thanks. I've done another review of the code. Almost there. These should be easier to fix.

2022-03-05 15:27 UTC, aster-phoenix commented
@radcortez I have updated the PR

2022-03-10 15:11 UTC, radcortez commented
Hi @aster-phoenix, Sorry again. I think we only have one last thing to fix and we are good to go. Thank you for your patience.

2022-03-10 15:32 UTC, aster-phoenix commented
Hi @radcortez, I updated PR, closed statements in finally block, but ResultSet should be auto closed since it's defined in try with resources, right?

2022-03-10 17:05 UTC, radcortez approved these changes

2022-03-10 17:33 UTC, merged

2022-03-10 17:47 UTC, aster-phoenix commented
Thank you for your time, effort and valuable input, and my apologies for going back and forth multiple times.